### ISSUE TITLE
Základní milestone

### ISSUE THREAD

**Issue by czmirek** [czmirek/PersonalDataDB#1]
- [X] Inicializace struktury osobních údajů, zatím hardcoded.
- [X] InMemory repozitář
- [X] Vložení osobního údaje
- [X] Přečtení osobního údaje dle zadané cesty
- [X] Schéma musí znát repozitář i PDDB Driver
- [X] Test na vložení a zápis

**Comment by czmirek** [comment]
- [X] Změna údaje v jedné buňce nebo ve zvolených hodnotách v celém řádku
- [X] Přečtení hodnot pouze z uvedených sloupců
- [X] Přečtení jedné hodnoty pouze z jednoho sloupce
- [X] Názvy tabulek a sloupců a kontorly musí být case sensitive, nezávisle na data providerovi
- [X] Kontrola existence požadovaných sloupců při čtení hodnot
- [X] Kontrola vyplnění všech hodnot při vložení
- [X] Kontrola nullable hodnot na úrovni PDDB
- [X] Kontrola povinných údajů v rámci celého řádku
- [X] Kontrola existence tabulek a sloupců při manipulaci s daty
- [ ] TESTY na každý výše uvedený bod

**Comment by czmirek** [comment]
- [ ] CreateDatabase() - Definice schématu a metoda pro přímou inicializaci v data providerovi. Nelze inicializovat, pokud už je data provider jednou inicializován.
- [ ] Build() - Kontrola, že schéma tabulek odpovídá schématu v data providerovi.
- [ ] CreateDatabaseIfNotExist() - totéž jako CreateDatabase() akorát to databázi nevytvoří, pokud již existuje
- [ ] UpdateDatabase() - definice dílčích změn ve schématu - přidání sloupce, přidání tabulky, odstranění sloupce, odstranění tabulky.
- [ ] 

- [ ] Každá změna ve schématu musí být zalogovaná
- [ ] 
- [ ] Verzování schématu
- [ ] Přidání sloupce
- [ ] Přidání tabulky
- [ ] Odstranění sloupce
- [ ] Odstranění tabulky
- Databáze se vytvoří jednou.
- Pro to je potřeba specifikovat schéma a administrátora nebo zodpovědnou osobu za vytvoření schématu.
- Update schématu - při odstranění sloupců je třeba kontrolovat existující účely,  

Administrátor

Účely

- [ ] Globální účely pro čtení, držení a zápis vztahující se na všechna data.
- [ ] Omezení účelu na tabulku, sloupec, řádek, buňku.
- [ ] Druh účelu: držení, čtení, vložení, změna, smazání
- [ ] Omezení čtení dat, pokud chybí účel pro čtení
- [ ] Omezení vložení/změny dat, pokud chybí účel pro držení
- [ ] Omezení smazání/editace účelu, pokud už jsou na tento účel napojena nějaká osobní data (v budoucnu lze vymyslet něco jako automatické odeslání emailu vlastníkovi dat, dle konfigurace)

Co dál: logování, důvody, uživatelé, administrátor, konfigurace, jednorázové účely, souhlasy a důkazy, šifrování, otázky a odpovědi, attach
Co dál: API pro správce, vlastníka, uživatele
Co dál: SQLite
Co dál: manipulace dat přes anonymní objekty
